name = "atlangrove"
main = "worker/src/index.ts"
compatibility_date = "2024-03-18"

[vars]
ENV = "production"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "atlangrove_db"
database_id = "8ce477f7-bdfa-43cf-b231-3de132211292"
migrations_dir = "worker/migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "atlangrove-media"
